replicaCount: 1
image:
  repository: ghcr.io/timmyspence/rate-my-guinness
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
db:
  image: postgres:15
  user: postgres
  password: postgres
  db: guinness
  port: 5432
resources: {}
