apiVersion: v1
kind: Service
metadata:
  name: {{ include "rate-my-guinness.fullname" . }}
  labels:
    app: {{ include "rate-my-guinness.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "rate-my-guinness.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rate-my-guinness.fullname" . }}-db
  labels:
    app: {{ include "rate-my-guinness.name" . }}-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: {{ include "rate-my-guinness.name" . }}-db
