name: Deploy to GKE via Helm (Image Trigger)

on:
  repository_dispatch:
    types: [ghcr-image-pushed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials guinness-autopilot --region ${{ secrets.GCP_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade --install rate-my-guinness ./chart \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/rate-my-guinness \
            --set image.tag=latest \
            --namespace rmg --create-namespace
