name: Deploy to GKE via Helm (Image Trigger)

on:
  repository_dispatch:
    types: [ghcr-image-pushed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Set lowercase repo owner
        id: repo
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials guinness-autopilot --region ${{ secrets.GCP_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Ensure rmg namespace exists
        run: |
          kubectl get namespace rmg || kubectl create namespace rmg

      - name: Create GHCR image pull secret
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.GHCR_USERNAME }} \
            --docker-password=${{ secrets.GHCR_PAT }} \
            --docker-email=${{ secrets.GHCR_EMAIL }} \
            --namespace=rmg --dry-run=client -o yaml | kubectl apply -f -

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade --install rate-my-guinness ./chart \
            --set image.repository=ghcr.io/${{ steps.repo.outputs.owner }}/rate-my-guinness \
            --set image.tag=latest \
            --namespace rmg --create-namespace
