name: Secret Scanning with truffleHog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run truffleHog
        uses: trufflesecurity/trufflehog@v3.90.1
        with:
          scanArguments: --no-update --json .
